apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./base/sales-api/

patchesStrategicMerge:
- ./overlays/sales-api.yaml

images:
- name: sales-api-image
  newName: dev.local/sales-api-amd64
  newTag: "1.1"
